version: 2

jobs:
  build:
    working_directory: ~/notebook

    docker:
      - image: node:10.15.3
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
          LANG: ja_JP.UTF-8
          LC_ALL: C.UTF-8
          LANGUAGE: ja_JP.UTF-8

    branches:
      only:
        - master

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-

      - run:
          name: Install Node dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_moduels
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: yarn lint

      # FIXME: Enable to deploy expo app from CI (#44)
      # - run:
      #     name: Build
      #     command: yarn build
      #
      # - run:
      #     name: Deploy master branch to GitHub Pages
      #     command: yarn deploy:ci
